Entity/IntegrationAwareInterface.php
<?php

namespace Sellry\MagentoRma\Entity;

use Oro\Bundle\IntegrationBundle\Entity\Channel as Integration;

interface IntegrationAwareInterface
{
    /**
     * @param Integration $integration
     * @return IntegrationAwareInterface
     */
    public function setChannel(Integration $integration);

    /**
     * @return Integration
     */
    public function getChannel();

    /**
     * @return string
     */
    public function getChannelName();
}

Resources/views/Customer/index.html.twig
{% extends 'OroUIBundle:actions:index.html.twig' %}

{% import 'OroUIBundle::macros.html.twig' as UI %}

{% set pageTitle = 'orocrm.magento.customer.entity_plural_label'|trans %}
{% set gridName = 'magento-customers-extended-grid' %}

{% block navButtons %}
    {% if resource_granted('orocrm_magento_customer_create') %}
        <div class="btn-group">
            {{ UI.addButton({
                'path' : path('orocrm_magento_customer_create'),
                'entity_label': 'orocrm.magento.customer.entity_label'|trans
            }) }}
        </div>
    {% endif %}
{% endblock %}

Resources/views/Customer/view.html.twig
{% extends 'OroUIBundle:actions:view.html.twig' %}
{% import 'OroUIBundle::macros.html.twig' as macros %}
{% import 'OroEmailBundle::macros.html.twig' as email %}

{% set fullname = entity|oro_format_name|default('N/A'|trans) %}
{% oro_title_set({params : {"%customer.name%": fullname} }) %}

{% block navButtons %}
    {% if entity.originId and entity.channel.transport.adminUrl|default(false) %}
        {{
            UI.clientButton({
                'dataUrl': path('orocrm_magento_customer_orderplace', {'id': entity.id }),
                'aCss':    'no-hash',
                'iCss':    'icon-money',
                'dataId':  entity.id,
                'label' : 'orocrm.magento.customer.create_order'|trans,
                'widget' : {
                    'type' : 'dialog',
                    'options' : {
                        'alias':               'transaction-dialog',
                        'stateEnabled':        false,
                        'incrementalPosition': true,
                        'loadingMaskEnabled':  false,
                        'dialogOptions' : {
                            'dialogClass':   'place-order-transaction-dialog',
                            'title' :        'orocrm.magento.customer.create_order'|trans,
                            'allowMaximize': true,
                            'allowMinimize': false,
                            'width':         1000,
                            'height':        600,
                            'modal':         true,
                            'autoResize':    true
                        }
                    }
                }
            })
        }}
    {% endif %}
    {% include 'OroCRMMagentoBundle:NewsletterSubscriber:buttons.html.twig' with { entity: entity.newsletterSubscriber, customer: entity } %}
    {% if resource_granted('EDIT', entity) %}
        {{ UI.editButton({
            'path' : path('orocrm_magento_customer_update', { 'id': entity.id }),
            'entity_label': 'orocrm.magento.customer.entity_label'|trans
        }) }}
    {% endif %}
    {{ parent() }}
{% endblock navButtons %}

{% block pageHeader %}
    {% set breadcrumbs = {
        'entity': entity,
        'indexPath': path('orocrm_magento_customer_index'),
        'indexLabel': 'orocrm.magento.customer.entity_plural_label'|trans,
        'entityTitle': fullname
    } %}
    {{ parent() }}
{% endblock pageHeader %}

{% block stats %}
    {{ parent() }}
    <li>
        <div class="pull-right label label-info orocrm-channel-lifetime-value-label">
            {{ 'orocrm.magento.customer.lifetime.label'|trans}}: {{ entity.lifetime|oro_format_currency }}
        </div>
    </li>
    {% include 'OroCRMAnalyticsBundle::label.html.twig' %}
{% endblock stats %}

{% block content_data %}
    {% set customerInformationWidget %}
        {{ oro_widget_render({
            'widgetType': 'block',
            'url':         path('orocrm_magento_customer_info', {id: entity.id})
        }) }}
    {% endset %}

    {% set generalSubBlocks = [{'data' : [customerInformationWidget]}] %}

    {% set salesTabsWidget %}
        <div class="responsive-cell" id="magento-without-border-tabs">
            {% set tabs = [
                {
                    'alias': 'orocrm_magento_customer_orders',
                    'widgetType': 'block',
                    'label': "orocrm.magento.order.entity_plural_label"|trans,
                    'url': path(
                            'orocrm_magento_customer_orders_widget',
                            {'customerId': entity.id, 'channelId': entity.channel.id}
                    )
                },
                {
                    'alias': 'orocrm_magento_customer_carts',
                    'widgetType': 'block',
                    'label': "orocrm.magento.cart.entity_plural_label"|trans,
                    'url': path(
                        'orocrm_magento_customer_carts_widget',
                        {'customerId': entity.id, 'channelId': entity.channel.id}
                    )
                }
            ] %}
            {{ tabPanel(tabs) }}
        </div>
    {% endset %}
    
    {% set rmasTabsWidget %}
        <div class="responsive-cell" id="magento-without-border-tabs">
            {% set tabs = [
                {
                    'alias': 'orocrm_magento_customer_rma',
                    'widgetType': 'block',
                    'label': "RMAs"|trans,
                    'url': path(
                            'orocrm_magento_customer_rma_widget',
                            {'customerId': entity.id}
                    )
                }
            ] %}
            {{ tabPanel(tabs) }}
        </div>
    {% endset %}


    {% set casesTabsWidget %}
        <div class="responsive-cell" id="magento-without-border-tabs">
            {% set tabs = [
            {
                'alias': 'sellry_case',
                'widgetType': 'block',
                'label': "Cases"|trans,
                'url': path(
                        'sellry_case_case_widget',
                        {'customerId': entity.id}
                    )
            }
            ] %}
            {{ tabPanel(tabs) }}
        </div>
    {% endset %}

    {% set customerAddressBookWidget %}
        <div class="responsive-cell">
            {{ oro_widget_render({
                'widgetType': 'block',
                'contentClasses': [],
                'url': path('orocrm_magento_customer_address_book', {id: entity.id}),
                'title': 'orocrm.magento.customer.address_book.title'|trans
            }) }}
        </div>
    {% endset %}
    {% set generalSubBlocks = generalSubBlocks|merge([{'data': [customerAddressBookWidget]}]) %}

    {% set dataBlocks = [
        {
            'title': 'General Information'|trans,
            'class': 'active',
            'subblocks': generalSubBlocks
        },
        {
            'title': 'orocrm.magento.customer.sales.label'|trans,
            'subblocks': [
                {'data' : [salesTabsWidget] }
            ]
        },
        {
            'title': 'RMAs'|trans,
            'subblocks': [
                {'data' : [rmasTabsWidget] }
            ]
        },        {
            'title': 'Cases'|trans,
            'subblocks': [
                {'data' : [casesTabsWidget] }
            ]
        },
    ] %}

    {% if entity.newsletterSubscriber is not empty %}
        {% set newsletterSubscriberBlock %}
            {{ oro_widget_render({
                'widgetType': 'block',
                'url': path('orocrm_magento_newsletter_subscriber_info', {id: entity.newsletterSubscriber.id})
            }) }}
        {% endset %}
        {% if newsletterSubscriberBlock %}
            {% set dataBlocks = dataBlocks|merge([
                {
                    'title': 'orocrm.magento.newslettersubscriber.label'|trans,
                    'subblocks': [
                        {'data' : [newsletterSubscriberBlock] }
                    ]
                }
            ]) %}
        {% endif %}
    {% endif %}

    {% set id = 'magentoCustomerView' %}
    {% set data = {'dataBlocks': dataBlocks} %}
    {{ parent() }}
{% endblock content_data %}